name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

- name: Use Node.js 16
  uses: actions/setup-node@v2
  with:
    node-version: 16


    - name: Set up Go 1.21
      uses: actions/setup-go@v1
      with:
        go-version: 1.21
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - run: mkdir -p build

    - name: Build
      run: go build -v -ldflags "-w -s" -trimpath -o build/tg-keyword-reply-bot .
    
    - uses: actions/upload-artifact@v1
      with:
        name: bin
        path: build
